# Pra-Survei

## Keselamatan Kerja

Survei kehati seringkali dilakukan di daerah terisolir, jauh dari sarana umum dan kebutuhan akan bantuan medis profesional sulit dijangkau. Oleh karena itu penting untuk selalu sadar mengenai bahaya yang mengintai setiap saat, sehingga kita harus selalu waspada selama berkegiatan. Dibawah ini merupakan beberapa tips untuk dapat diikuti.

**Selalu bekerja bersama tim.** Jangan pernah melakukan pengamatan sendirian, pastikan minimal ada satu anggota lain yang ikut. Jika terjadi kecelakaan kerja, atau kondisi darurat, akan ada rekan kerja yang dapat memberikan pertolongan. Keberadaan rekan kerja juga mengurangi resiko tersesat saat pengamatan.

**Memberikan rencana perjalanan di luar tim.** Pastikan rekan kerja selain orang di luar tim survei, tahu rencana perjalanan dan kapan kalian akan kembali. Mereka dapat memberikan pertimbangan untuk melakukan evakuasi, jika kalian belum kembali dari waktu yang sudah direncakan. Rencana ini lebih baik jika ditulis detil hari per hari, sehingga mereka tahu perkiraan anda berada dimana pada suatu tanggal spesifik.

**Persiapkan peralatan keselamatan dengan seksama.** Pastikan membawa peta, kompas dan GPS jika ingin melakukan pengamatan di luar jalur. Membawa senter dan alat penerang jika estimasi perjalanan kalian hingga malam. Membawa peralatan pertolongan pertama jika berjalan jauh dari kamp utama. Membawa suplai makanan ekstra untuk melalui medan yang belum dikenal jika terdapat kelebihan hari.

**Persiapan untuk dapat memberikan pertolongan pertama.** Ada baiknya seluruh anggota tim, dilatih untuk dapat memberikan pertolongan pertama dengan benar dari pelaku medis profesional setempat (Dokter, petugas puskesmas, KSR PMI dll). Sehingga mereka sudah siap memberikan pertolongan kepada siapapun yang membutuhkan. Peralatan pertolongan pertama yang akan dibawa setidaknya mencakup; seperangkat peralatan penutup luka, tablet antibiotik, tablet malaria, bubuk rehidrasi, salep atau bedak anti jamur dan anti gatal, salep luka bakar dan *snake bite-kit*.

**Persiapkan jalur evakuasi.** Persiapkan rute evakuasi, seperti titik evakuasi terdekat, kendaraan yang sudah siap sedia untuk menjemput tim yang perlu dievakuasi, sarana medis yang akan digunakan, protokol komunikasi dll.

**Menggunakan tenaga lokal.** Masyarakat lokal yang memiliki rutinitas berkegiatan di hutan dapat memberikan masukan mengenai jalur yang akan digunakan dan akan lebih waspada terhadap kondisi di kawasan tersebut (Potensi pohon tumbang, area rawan longsor dll).

**Hindari organisme dan area berbahaya.** Meskipun tujuan survei adalah untuk kajian jenis-jenis ular sekalipun, hindari menangkap ular berbisa. Jika kalian ragu apakah hewan tersebut berbahaya atau tidak sebaikmya tetap dihindari. Beberapa tumbuhan juga dapat menyebabkan gatal-gatal seperti jenis-jenis jelatang (*Dendrocnide sp*), beberapa lebah ada yang membuat sarang disemak-semak yang apabila tersentuh akan menyerang. Semakin sering ke lapangan anda akan dapat menghindari kejadian-kejadian tersebut. Hindari mandi di area sungai yang berpotensi dihuni oleh buaya. Jangan membuat kamp diarea yang terdapat pohon mati atau berpotensi rubuh. Perhatikan penggunaan pisau tebas. Penggunaan pisau tebas saat membuka jalur seringkali melukai diri sendiri dan orang didekatnya. Selalu waspada dalam penggunaan pisau tebas, terlebih jika area yang dibuka merupakan semak-semak yang memiliki tingkat kekerasan dan kerapatan yang variatif.

**Kebersihan adalah prioritas.** Luka-luka kecil akibat duri atau gesekan kayu bisa memberikan infeksi jika tidak rutin dibersihkan dengan air dan sabun antiseptik. Kondisi dapur di area kamp juga harus diperhatikan, terkadang anggota tim membuang sampah organik sembarangan, hal ini dapat menyebabkan masalah pencernaan.

**TERPENTING. *Use common sense!*.** Seringkali kecelekaan terjadi karena hal yang dari awal dapat dihindari seperti menyebrang sungai deras tanpa pengaman, memanjat pohon untuk mencari sinyal, tersesat karena panik, memanjat tebing terjal tanpa bantuan tali dan lain-lain. Selalu ketahui batas diri masing-masing, anggota tim yang lain mungkin dapat melompat diantara celah tebing dengan mudah, atau melewati tebing hanya dengan menyebrangi sebatang kayu yang dijadikan jembatan, namun anda belum tentu dapat melewatinya. Merupakan pilihan yang bijak untuk berpikir mengenai keselamatan diri dan membuat alternatif pilihan terhadap hambatan yang ditemui.
