project:
  type: book
  output-dir: _book

book:
  title: "Panduan Survei Kehati"
  author: "Fauna & Flora`s Indonesia Programme"
  description: Panduan praktis mengenai survei keanekaragaman hayati
  reader-mode: true
  page-navigation: true
  search: true
  back-to-top-navigation: true
  sidebar: 
    logo: cover.png
    search: true
  sharing: [twitter, facebook, linkedin]

  chapters:
  - index.qmd
  - 01-pendahuluan.qmd
  - part: 01-terestrial/02-intro.qmd
    chapters:
    - 01-terestrial/03-rancangan-survei.qmd
    - 01-terestrial/04-protokol.qmd
    - 01-terestrial/05-pengelolaan-data.qmd
    - 01-terestrial/06-analisa-data.qmd
  - part: 02-camtrap/02-intro.qmd
    chapters:
    - 02-camtrap/02-rancangan-survei.qmd
    - 02-camtrap/03-protokol.qmd
    - 02-camtrap/04-pengelolaan-data.qmd
  - 07-referensi.qmd
  - part: 03-marine/02-intro.qmd
    chapters:
    - 03-marine/temporary.qmd
  - part: 99-lampiran/02-intro.qmd
    chapters:
    - 99-lampiran/08-lampiran1.qmd
    - 99-lampiran/10-lampiran3.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: 
      - theme.css
      - theme.scss
    fontsize: 1.1em
    linestretch: 1.7
    toc: true
    toc-title: "Daftar Isi"
    crossref: 
      fig-title: "Gambar"
      fig-prefix: "Gambar" 
      tbl-title: "Tabel"
      tbl-prefix: "Tabel"
      sec-prefix: "Bab"
      sec-labels: alpha
    author-title: "Penulis"
    
execute:
  enabled: true  
      
  docx:
    reference-doc: FFI_Word Template.docx

prefer-html: true
editor: visual