# Prakata {.unnumbered}

## Untuk siapa panduan ini?

Panduan ini disusun bagi para praktisi konservasi, peneliti, mahasiswa, serta siapa saja yang memiliki ketertarikan dalam melakukan survei keanekaragaman hayati (kehati), khususnya di lingkup kerja Fauna & Flora Indonesia Programme (FF’s IP).

Melalui panduan ini, kami ingin menetapkan standar minimum yang seragam dan akurat dalam pemantauan kehati, sehingga data yang dihasilkan dapat menjadi landasan kuat dalam pengambilan keputusan ilmiah dan kebijakan konservasi.

Panduan ini menguraikan pendekatan praktis untuk melakukan survei kehati, dengan fokus pada tiga bagian utama:

1.  **Bioma Terestrial**\
    Membahas metode survei konvensional di daratan yang memerlukan kehadiran langsung peneliti di lapangan, seperti pemantauan burung (avifauna), reptil dan amfibi (herpetofauna), mamalia, serta vegetasi. Setiap metode dijelaskan langkah demi langkah, lengkap dengan kelebihan, keterbatasan, serta contoh penerapan.

2.  **Bioma Laut (Marine)**\
    Mengulas secara ringkas metode survei untuk ekosistem laut, termasuk pengamatan terumbu karang, padang lamun, hingga survei fauna laut seperti ikan dan mamalia laut. Bagian ini memberikan gambaran awal sebagai landasan pengembangan panduan lebih lanjut di masa depan.

3.  **Penggunaan Kamera Intai (*Camera Trap*)**\
    Walaupun kamera intai dapat digunakan di bioma terestrial, panduan ini memberikan pembahasan terpisah karena teknik pemasangan, pengambilan data, hingga analisisnya memiliki kompleksitas tersendiri.

    Kami menyadari bahwa metode survei kehati terus berkembang seiring kemajuan teknologi dan ilmu pengetahuan. Oleh karena itu, panduan ini bersifat *living document* yang akan terus diperbarui berdasarkan masukan dan pengalaman para praktisi. Kami sangat terbuka terhadap saran, kritik, ataupun laporan isu dari para pembaca. Silakan kirimkan kontribusi Anda melalui[email](mailto:ryan.avriandy@fauna-flora.org) atau laman [github kami](https://github.com/ryanavri/surveikehati).

## Hak Cipta dan Sitasi

Panduan ini lahir berkat kerja keras dan kolaborasi Tim Biodiversitas Fauna & Flora Indonesia Programme, dengan dukungan banyak pihak, termasuk tim penyusun dan editor yang berkomitmen mendukung upaya konservasi keanekaragaman hayati.

Kontributor utama yang telah memberikan masukan dan dukungan dalam penyusunan panduan ini meliputi:\
Ady Kristanto, Andhy Sayogo, Andri Irawan, Arief Hamidi, Dwiyanto, Fransisca Noni, Jarian Permana, Ryan Avriandy, Yanuar Ishaq Dwi Cahyo, Yogi Satrio Wibowo, dan Zana Pandya Pratisara, bersama tim editor yang dipimpin oleh \[Nama Editor akan dicantumkan kemudian\].

Kami mendorong para pembaca untuk menyebarluaskan buku ini seluas-luasnya demi mendukung upaya konservasi dan pemantauan keanekaragaman hayati di berbagai lokasi. Buku ini boleh didistribusikan dan dibagikan, asalkan mencantumkan kredit kepada penyusun dan kontributor.

Untuk sitasi, silakan gunakan format berikut:

``` markdown
Fauna & Flora Indonesia Programme. (2025). Panduan Survei Keanekaragaman Hayati. (Versi 0.1). https://doi.org/10.59350/zs7da-c67.
```

``` markdown
@online{faunaflora2025,
  author = {Fauna & Flora Indonesia Programme},
  title = {Panduan Survei Keanekaragaman Hayati},
  year = {2025},
  version = {0.1},
  publisher = {Fauna & Flora Indonesia Programme},
  url = {https://doi.org/10.59350/zs7da-177},
  doi = {10.59350/zs7da-167},
  langid = {id}
}
```
